### ISSUE TITLE
请问能不能加入自定义Webhook的功能

### ISSUE THREAD

**Issue by dakkidaze** [Bluefissure/DFAssist_CN#1]
配合IFTTT就能在手机上收通知了（

**Comment by Bluefissure** [comment]
请麻烦下呆萌dalao，这边没在维护DFA 23333
You can turn to https://github.com/DieMoe233/DFAssist_CN for a much more powerful DFAssist_CN.

或者可以用ACT插件[ACTFate](https://github.com/Bluefissure/ACTFate)，那边有自定义上报地址。
